### PR TITLE
Merge upstream and deindent case labels

### PR DESCRIPTION
**Pull request by BenFradella**

### CODE REVIEW

**Comment by rluba** [comment]
Thanks! I indent the case labels deliberately. But I understand that not everyone does. Maybe this should be an option?

**Comment by BenFradella** [comment]
Yeah, that sounds like a good way to do it

**Comment by BenFradella** [comment]
Alrighty. Added a dictionary with indentation options (and added `;` to `indentkeys` -- missed that before)
Case indentation can be disabled by setting the `case_labels` key to 0, e.g.: `let b:jai_indent_options = {'case_labels':0}`

**Comment by rluba** [comment]
Thanks! It took me a while…

I’ve inverted the default case (since that seems to be jai’s default atm) and also fixed de-indentation.

(I’ve also removed the `new` and `delete` keywords you added, since those don't exist in jai.)

**Pull request merged**
